apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-example
  template:
    metadata:
      labels:
        app: go-example
    spec:
      containers:
      - name: go-example
        image: gcr.io/{PROJECT_ID}/go-example:1.0
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 8080